### ISSUE TITLE
On the scenario outlined in your presentation at Elixir London

### ISSUE THREAD

**Issue by lpil** [meadsteve/chaos-spawn#21]
Hello! Sorry about the issue, it seems I don't have your email.

I was thinking about the situation you described where the storage process went down and was slow enough to come back up that the supervisor gave up on the http request accepting process.

Did you come l decide on a solution? I know very little of otp, and I'm not sure what I would do here.

Cheers,
Louis

**Comment by meadsteve** [comment]
@lpil It has a couple of solutions I could think of: 
1. Have the data storage process respond in an appropriate way whilst it's reloading data. Maybe a message giving an estimated time to try again.
2. Allow the worker to fail a bit more. This is configurable in a few ways. You can set it to infinitely restart or just bump the allowed number of restarts. Should be documented here: http://elixir-lang.org/docs/stable/elixir/Supervisor.Spec.html under options.

The example was partly contrived to show that processes could have knock on effects to each other so that supervision alone doesn't save you. 

The main purpose for me creating this tool is to try and flush out these problems that might otherwise be hidden.

Also feel free to email me on github@meadsteve.io

**Comment by lpil** [comment]
Yes, that makes sense. Thanks Steve :)
